remove default UFO stores from query params
glmn/wb-private-api pull request #22
Opened 2023-01-19 21:04 UTC by abuntakov

2023-01-19 23:56 UTC, glmn commented
Какая зависимость в данному примере от stores? Выдача WB меняется?

2023-01-20 09:46 UTC, glmn requested changes

2023-01-20 14:54 UTC, abuntakov commented on src/WBPrivateAPI.js
> +    const params = {
а если понадобится сделать поиск в конкретном регионе или store'е?

2023-01-21 01:03 UTC, glmn commented on src/WBPrivateAPI.js
> +    const params = {
Согласен, `stores` и `regions` оставить можно.
По хорошему для `filters` подобрать значение, при котором тело ответа будет еще меньше. На данные момент знаю только про **fdlvr**.

P.S. Есть понимание что такое `couponsGeo`?

2023-01-22 10:56 UTC, abuntakov commented on src/WBPrivateAPI.js
> +    const params = {
удалил stores, добавил fulters=fdlvr

2023-01-22 12:54 UTC, merged